### ISSUE TITLE
Implementación de KNN-RTree

### ISSUE THREAD

**Issue by diegorandolp** [MitsuoMurakami/Proyecto_DB2#11]
## Indexación con R-Tree

- [x] Evaluar Alternativas: Decidir entre R-Tree en C++, Python o el índice GiST en PostgreSQL. De preferencia el de Python para una integración más rapida.
- [x] Implementar Indexación: Crear el índice R-Tree para los vectores característicos.
- [x] Pruebas de Indexación: Verificar la eficiencia y efectividad del R-Tree en búsquedas.

**Comment by MilloshyC-UTEC** [comment]
terminado
